# Flange to Mount to Injector

In [7]:
import numpy as np
import pandas as pd
from margins import margins
pd.options.display.float_format = '{:.3f}'.format

### Force Balance

In [8]:
p_c = np.array([300, 500]) #chamber pressure [psi]

d_mean = np.mean([0.676, 0.556]) # mean diameter of o-ring [in]
A_pres = np.pi * (d_mean/2) **2 #Area force is acting on [in]

#Forces on Torch [lbf]
F_pres = p_c * A_pres #Net Force on Chamber
Thrust = 100.031
F_net = F_pres + Thrust

df_force = pd.DataFrame({
    "Chamber Pressure [psi]": p_c,
    "Net Pressure Force [lbf]": F_pres, 
    "Net Force [lbf]": F_net
})
print(f"Pressure Area: {A_pres:0.3f} in^2")
print(f"Thrust: {Thrust:0.3f} [lbf]")

df_force

Pressure Area: 0.298 in^2
Thrust: 100.031 [lbf]

   Chamber Pressure [psi]  Net Pressure Force [lbf]  Net Force [lbf]
0                     300                    89.407          189.438
1                     500                   149.012          249.043

### Fastener Details

In [9]:
# Bolt Details
bolt_yield = 30000 # 18-8 SS yield[psi]
bolt_area = 0.014 # size #8-32 UNC tensile stress area [in^2]
N = 6 # bolt count

In [10]:
# Bolt Yielding
SF = 2.5 #safety factor

sigma_bolt = (F_net / N) / bolt_area
FoS = (bolt_yield / sigma_bolt)
margin = margins(SF,bolt_yield, sigma_bolt)

df_stress = pd.DataFrame({
    "Chamber Pressure [psi]": p_c, 
    "Net Force [lbf]": F_net,
    "Bolt Stress [psi]": sigma_bolt,
    "Yield Margin [%] ": margin,
    "Actual FoS": FoS
})
print("Bolt Yielding")
print("Count:", N)
print("Design FoS:", SF)
df_stress

Bolt Yielding
Count: 6
Design FoS: 2.5

,Chamber Pressure [psi],Net Force [lbf],Bolt Stress [psi],Yield Margin [%],Actual FoS
0,300,189.438,2255.217,432.100,13.302
1,500,249.043,2964.798,304.749,10.119