# Flange to Mount to Injector

In [5]:
import numpy as np
import pandas as pd
from margins import margins
pd.options.display.float_format = '{:.3f}'.format

### Force Balance

In [6]:
p_c = np.array([300, 500]) #chamber pressure [psi]

d_mean = np.mean([0.676, 0.556]) # mean diameter of o-ring [in]
A_pres = np.pi * (d_mean/2) **2 #Area force is acting on [in]

#Forces on Torch [lbf]
F_pres = p_c * A_pres #Net Force on Chamber
Thrust = 15.94
F_net = F_pres + Thrust

df_force = pd.DataFrame({
    "Chamber Pressure [psi]": p_c,
    "Net Pressure Force [lbf]": F_pres, 
    "Net Force [lbf]": F_net
})
print(f"Pressure Area: {A_pres:0.3f} in^2")
print(f"Thrust: {Thrust:0.3f} [lbf]")

df_force

Pressure Area: 0.298 in^2
Thrust: 15.940 [lbf]

   Chamber Pressure [psi]  Net Pressure Force [lbf]  Net Force [lbf]
0                     300                    89.407          105.347
1                     500                   149.012          164.952

### Fastener Details

In [7]:
# Bolt Details
bolt_yield = 30000 # 18-8 SS yield[psi]
bolt_area = 0.006 # size #4 UNCtensile stress area
N = 4 # bolt count

In [9]:
# Bolt Yielding
SF = 2.5 #safety factor

sigma_bolt = (F_net / N) / bolt_area
FoS = (bolt_yield / sigma_bolt)
margin = margins(SF,bolt_yield, sigma_bolt)

df_stress = pd.DataFrame({
    "Chamber Pressure [psi]": p_c, 
    "Net Force [lbf]": F_net,
    "Bolt Stress [psi]": sigma_bolt,
    "Yield Margin [%] ": margin,
    "Actual FoS": FoS
})
print("Bolt Yielding")
print("Count:", N)
print("Design FoS:", SF)
df_stress

Bolt Yielding
Count: 4
Design FoS: 2.5

,Chamber Pressure [psi],Net Force [lbf],Bolt Stress [psi],Yield Margin [%],Actual FoS
0,300,105.347,4389.467,173.382,6.835
1,500,164.952,6873.001,74.596,4.365