In [2]:
import numpy as np
import pandas as pd
from margins import margins

pd.options.display.float_format = '{:.3f}'.format
MM2IN = 0.0393701

# CHAMBER (304 Stainless Steel)

In [3]:
#From Nickel Institute: 
sigma_temp = 9900

# approximate as thick walled cylinder
p = np.array([300, 500]) #pressure [psi]

r_i = 0.377 # radius [in]
r_o = 1.654/2 # outer radius [in] (approximate as the outer radius of a cylinder)


# Compute von mises stress
sigma_hoop = p*(r_o**2 + r_i**2) / (r_o**2 - r_i**2)
sigma_axial = p * r_i**2 / (r_o**2 - r_i**2)
sigma = ((sigma_hoop**2 + sigma_axial**2 + p**2 - sigma_hoop*sigma_axial + p*sigma_hoop + p*sigma_axial))**0.5

SF = 2.5
FOS_actual =  sigma_temp / sigma
margin = margins(SF, sigma_temp, sigma)
df_Stress = pd.DataFrame({
    "Chamber Pressure[psi]":p,
    "Design Stress [psi]": sigma,
    "Yield Margin [%]": margin,
    "Actual FoS": FOS_actual
})

print("Design FoS:", SF)
print(f"Wall Thickness {r_o-r_i:0.3f} in")
df_Stress

Design FoS: 2.5
Wall Thickness 0.450 in

   Chamber Pressure[psi]  Design Stress [psi]  Yield Margin [%]  Actual FoS
0                    300              655.925           503.728      15.093
1                    500             1093.208           262.237       9.056

# Flame Tube (Copper 715)

In [4]:
#Nickel Institue
sigma_temp = 20000 #[psi]

# thick walled cylinder
p = np.array([300,500]) #pressure [psi]

r_o = 0.477 # actual thickness [in] 
r_i = 0.148 # radius [in]


# Compute von mises stress
sigma_hoop = p*(r_o**2 + r_i**2) / (r_o**2 - r_i**2)
sigma_axial = p * r_i**2 / (r_o**2 - r_i**2)
sigma = ((sigma_hoop**2 + sigma_axial**2 + p**2 - sigma_hoop*sigma_axial + p*sigma_hoop + p*sigma_axial))**0.5

SF = 2.5
FOS_actual =  sigma_temp / sigma
margin = margins(SF, sigma_temp, sigma)
df_Stress = pd.DataFrame({
    "Chamber Pressure[psi]":p,
    "Design Stress [psi]": sigma,
    "Yield Margin [%]": margin,
    "Actual FoS": FOS_actual
})

print("Design FoS:", SF)
print(f"Wall Thickness {r_o-r_i:0.3f} in")
df_Stress

Design FoS: 2.5
Wall Thickness 0.329 in

   Chamber Pressure[psi]  Design Stress [psi]  Yield Margin [%]  Actual FoS
0                    300              574.967          1291.385      34.785
1                    500              958.278           734.831      20.871